### ISSUE TITLE
Comparison functions

### ISSUE THREAD

**Issue by b00108011** [sptonkin/fuzzyhashlib#4]
Hi,
I am trying to compare two Sdhash digests generated with the library in Python
i.e. to get their similarity score

How do I do this?

**Comment by sptonkin** [comment]
This definitely wasn't clear in the library's documentation, sorry. Versions 0.0.7 and earlier used the subtraction operator ("-") on the fuzzy hash objects to do a comparison. I've had a couple of requests for a .compare() method so just pushed out version 0.0.8 which:

- Implements a .compare() method on fuzzy hash objects alongside comparison with subtraction, and
- Included examples of comparisons in the documentation.

Thanks for letting me know!
